### ISSUE TITLE
rename: DateTime => Timestamp, Datetime => DateTime?

### ISSUE THREAD

**Issue by StefanKarpinski** [quinnj/Datetime.jl#11]
Since the differing-only-by-capitalization thing is a bit awkward. Just a thought.

**Comment by quinnj** [comment]
Yeah, I agree it's a big awkward. I do kinda like Timestamp now that you mention it. It would also be interesting to see if something comes out of @kmsquire's recent post: https://groups.google.com/forum/#!searchin/julia-users/Datetime/julia-users/4dU4ykxEMrg/NkUIpJCKeA0J

**Comment by StefanKarpinski** [comment]
I suspect that in the short term, this won't change since it's a breaking change and we're trying (with limited success) to quiet things down for a 0.2 release.

**Comment by quinnj** [comment]
Official name is `DateTime`, the new module will be names `Dates`

**Comment by kmsquire** [comment]
It hasn't gotten much feedback/press, but when you go about renaming DateTime, please consider https://github.com/JuliaLang/METADATA.jl/issues/347#issuecomment-35015012.

Renaming `Stats` to `StatsBase` caused a number of headaches, and something like the proposal in that link should prevent future headaches. 

(@StefanKarpinski, it would be great if you could comment on that at some point.)

**Comment by quinnj** [comment]
Hey @kmsquire, thanks for the link, though I don't think there is the RetiredPackages infrastructure in place. What would you suggest as the best way to go about renaming? How about the following:

-Rename the Datetime.jl repo to Dates.jl
-Tag a new release branch in the new repo for old Datetime.jl code, plus a deprecated package warning when package is loaded
-Bump Datetime in METADATA to new version, specifying min/max of julia _as well as changing the url to the new repo_ (<= would this have unintended consequences?)
-Register Dates.jl in METADATA, with new repo url and pointing to latest commit
-Profit!
-Spend several weeks resolving ripple effects in other packages
-Regret ever changing package name

Just kidding on the last few (I think...)

**Comment by StefanKarpinski** [comment]
I think we should just leave Datetime.jl around as a legacy package and either fork it to create Dates.jl, or start from a clean slate, copying code over as necessary. (I often like to start with a clean slate and copy code rather than trying to modify a large code base.) I don't think we should deprecate Datetime.jl. Instead, we should mark it as only being compatible with Julia 0.3 and earlier. Dates.jl will only support Julia 0.4 and up. That way there's a clean break and anyone who wants to port date/time code from Julia 0.3 to 0.4 needs to switch from Datetime.jl to the new Base date/time types and Dates.jl.

**Comment by quinnj** [comment]
That sounds like a good plan. Any ETA on 0.3 release?

**Comment by StefanKarpinski** [comment]
Not sure what the holdup is, but imo, we should do an RC any day now...

**Comment by kmsquire** [comment]
Sorry not to respond earlier.  New job is keeping me away from Julia more than I would like.

Anyway, I like Stefan's plan, and I suspect package renaming policy will work itself out (though maybe after a few more things break ;-)  Cheers!
