### ISSUE TITLE
How to access milliseconds?

### ISSUE THREAD

**Issue by spmacdonald** [quinnj/Datetime.jl#16]
You say in the documentation that the Datetime has millisecond precision but I do not see how to construct a Datetime with milliseconds, for example:

   2009-11-02T09:30:00.001

How can I construct this datetime?

**Comment by quinnj** [comment]
Ok, you should be able to specify the millisecond portion for the DateTime now. DateTime was just recently change from second to millisecond precision, hence the lack of ability to construct with that component. Let me know if you see any other holes with millisecond support. Thanks!

**Comment by quinnj** [comment]
I updated the manual as well, so hopefully this is all propagated through now.

**Comment by spmacdonald** [comment]
Thanks for the quick fix!
