### ISSUE TITLE
Should we try to find out the user's timezone somehow?

### ISSUE THREAD

**Issue by quinnj** [quinnj/Datetime.jl#2]
Right now the default timezone is always UTC, which is good for performance reasons, but it could be expected that the default timezone be whatever the user's system is set to. I'm pretty sure there are C routines to check this somehow that we could tap into if we wanted.

**Comment by aviks** [comment]
`function _default_zone()`

https://github.com/aviks/SimpleDate.jl/blob/master/src/SimpleDate.jl#L126

which is then called at module init.

**Comment by quinnj** [comment]
Nice. Thanks for the tip @aviks. I guess this brings up a bigger question of when/where/if we should get and use the user's timezone. I think I lean towards not using it as much as possible, but I think the one case which makes sense is the `now()` function.

**Comment by quinnj** [comment]
This is implemented in the Dates.jl package in `now()`
