### ISSUE TITLE
dayofweek() return value inconsistent with day definition for Sunday

### ISSUE THREAD

**Issue by msravi** [quinnj/Datetime.jl#32]
Seems like the return value of dayofweek() is inconsistent with the day definition for Sunday. dayofweek() returns 0 for Sunday, while Sunday is defined as 7.

julia> using Datetime

julia> dt=date("2014-01-05")
2014-01-05

julia> dayofweek(dt)
0

julia> Sunday
7

Regards,
Ravi

**Comment by quinnj** [comment]
This is fixed in JuliaLang/julia#5328 as well.

**Comment by quinnj** [comment]
Fixed by ed8123ede2e316a181a781ecd54fd735657b6cd8
