### ISSUE TITLE
Access violation when calling in(date, interval) with a composite type field as interval

### ISSUE THREAD

**Issue by accerqueira** [quinnj/Datetime.jl#42]
Hi!

The full code used to test this, and outputs on Windows XP with Julia v0.2.1 and Julia v0.3.0-prerelease+2402 is here:
https://gist.github.com/accerqueira/11403761d7cda61dcfc1

The strangest thing for me, was that 

``` julia
function day_in(day::Date, obj::ObjMember)
  interval = obj.member
  return day_in(day, interval)
end

function day_in(day::Date, interval::DateRange1)
  return day_in(day, [interval])
end

function day_in{C}(day::Date{C}, interval::Array{Date{C}, 1})
  return day in interval
end
```

worked, but

``` julia
function day_in(day::Date, obj::ObjMember)
  interval = [obj.member] # cool
  return day in interval # not cool
end
```

didn't.

Maybe there is something wrong with my installation or my code, although I think Julia is supposed to not let this kind of violations happen... I'm posting here because I couldn't come up with a code that would give this error without Datetime being used...

**Comment by quinnj** [comment]
Thanks for the report. I'll look into this.

**Comment by accerqueira** [comment]
Just tested on Linux, and the same thing happened, except that instead of an exception, it just segfaulted without any aditional details.
This looks like a bug in Julia, and maybe me abusing something... Should I post there?

**Comment by quinnj** [comment]
I reported it. I can't seem to see what's going on.

**Comment by quinnj** [comment]
Link: https://github.com/JuliaLang/julia/issues/6387

**Comment by quinnj** [comment]
This has been fixed in Base Julia. Thanks for reporting.
