### ISSUE TITLE
Construct datetime from string

### ISSUE THREAD

**Issue by milktrader** [quinnj/Datetime.jl#43]
The `date` method takes a string as argument and creates a `Date{ISOCalendar}` object, but the same doesn't hold true for `datetime`

``` julia
julia> string(date(1999,1,1))
"1999-01-01"

julia> date(ans)
1999-01-01

julia> string(datetime(1999,1,1,12,12,12,0,EST))
"1999-01-01T12:12:12 EST"

julia> datetime(ans)
ERROR: no method datetime(ASCIIString)
```

Is this method being implemented in the base PR?

**Comment by quinnj** [comment]
Sorry to be slow in responding. Yes, the new Dates.jl package already supports this. The plan as of now is to wrap up some loose ends and publish the package officially in about a month. I still need to do some final tweaks on the packages, but it's pretty usable right now if you wanted to check it out:

https://github.com/karbarcca/Dates.jl
