### ISSUE TITLE
Datetime depends upon a stable serialize across versions and platforms

### ISSUE THREAD

**Issue by mbauman** [quinnj/Datetime.jl#50]
In commit https://github.com/JuliaLang/julia/commit/bb67ff25e2799b27d10877692f74bae66ccc0270 the serialization format was changed, which is to be expected.  But this breaks loading Datetime as tzdata and leap seconds are stored in a serialized data file.  Perhaps the tzdata should be serialized on the first launch for each user?

**Comment by quinnj** [comment]
Yeah, I remember having the thought when I put them in a serialized format that this would probably end up breaking at some point. I don't think it'd be too bad to store them as plain text.

**Comment by quinnj** [comment]
Closed by #51.

**Comment by mbauman** [comment]
Thanks @lendle!
