### ISSUE TITLE
Can't use timezones on a 32 bit machine

### ISSUE THREAD

**Issue by w7dup** [quinnj/Datetime.jl#60]
Hi all,

I am using an older machine with "Ubuntu 14.04 LTS (GNU/Linux 3.13.0-30-generic i686)" installed. And I am using the julia install from the Ubuntu Apt repo. "Version 0.2.1 (2014-02-11 06:30 UTC) |  i686-linux-gnu"

When I try to use the now function AND pass a timezone I get the following error in the REPL:

julia> a=now(PDT)
Evaluation succeeded, but an error occurred while showing value of type DateTime{ISOCalendar,Zone109}:
ERROR: type: typeassert: expected (Int32...,), got (Int64,Int32)
 in deserialize at serialize.jl:391
 in handle_deserialize at serialize.jl:322
 in deserialize at serialize.jl:305
 in anonymous at no file:107
 in open at io.jl:342
 in getoffset at /home/mdenson/.julia/v0.2/Datetime/src/Timezone.jl:106
 in _days at /home/mdenson/.julia/v0.2/Datetime/src/Datetime.jl:224
 in string at /home/mdenson/.julia/v0.2/Datetime/src/Datetime.jl:257
 in show at /home/mdenson/.julia/v0.2/Datetime/src/Datetime.jl:263
 in anonymous at no file:945
 in with_output_limit at show.jl:922
 in showlimited at show.jl:944
 in writemime at repl.jl:2
 in display at multimedia.jl:117
 in display at multimedia.jl:119
 in display at multimedia.jl:151

A UTC works fine.

Thanks,
Matthew

**Comment by quinnj** [comment]
Should be fixed now. Sorry for the delay.
