### ISSUE TITLE
DateTime128 type

### ISSUE THREAD

**Issue by quinnj** [quinnj/Datetime.jl#8]
I think it could be potentially useful to have a 128-bit DateTime type with nanosecond precision. Java's new JSR-310 project which will be integrated into Java 8 _talked_ about  having a nanosecond precision type for their default (I couldn't tell if they actually implemented it or not).

Anyway, I'm postponing for now because until JuliaLang/julia#3081 get's resolved, I can hardly work with Int128s on Windows (I guess it could be a UInt128 though....)

**Comment by StefanKarpinski** [comment]
Another thought would be to support varying precision using a parametric timestamp type. This would be similar to the time mockup I made a while back: https://github.com/JuliaLang/julia/blob/master/examples/time.jl. That way you can control how much precision you get and keep the type only 64-bits large.

**Comment by quinnj** [comment]
Hmmm......one of my initial reactions is not wanting to add another parameter to `DateTime` as it already has `Calendar` and `Offsets` parameters.

I think it may be best to keep our `Date` type, `DateTime` type, and add a `DateTime128` type which all grow in precision (day, millisecond, nanosecond). I've also wanted to add a basic `Time` type that would take a `Calendar` parameter as well as a `Precision` parameter, similar to what you mocked up before (that was actually where I got the idea!). The `Time` type could support all the varying levels of precision.

**Comment by aviks** [comment]
Based on @StefanKarpinski 's idea, I'd done 

`type DateTime{T<:Real} ...`

with 

`typealias Date DateTime{Int}`  and `DateTime{Float64}` and the default type. 

https://github.com/aviks/SimpleDate.jl/blob/master/src/SimpleDate.jl#L29

However, I'm uncertain about the value of doing this as I personally never had an usecase for this. In fact, for very high resolution timestamps, I would probably eschew all type machinery and simply use (relatively measured) integers. On the other hand, that sounds like a cop out, and maybe we can do better in supporting a wider range of usecases than most current software?

**Comment by quinnj** [comment]
So I've been reworking some of the core API over the break and I've been thinking about this issue. One idea I have is to add another parameter to the DateTime type that would be "precision"; similar to other suggestions here. The parameter would be a Period type to specify the precision (with the package being shipped with Year-Millisecond Period types). Having DateTime parameterized by a Period type would allow people to define additional period types (Nanosecond, Yoctosecond, etc.) and use the same DateTime type at a different precision level.

Pros:
-DateTime becomes a nice generalized type that can handle different Calendars, Timezones and precision levels
-We actually support different precision levels at relatively small cost (though I'm not sure exactly how much work we'd actually be saving being able to use the same type)

Cons:
-It kinda feels like we're cramming too much into the type with 3 parameters; imagine having to write out the explicit constructor `DateTime{ISOCalendar,UTC,Millisecond}(value)`. That's quite a mouthful.
-It complicates the current code a bit by having to abstract out the precision level by dispatching to precision-specific constructors from the main constructor. This would also mean a bit of a performance hit, though probably not too much.

Anyway, I'm kind of leaning towards not having support for different precision levels (except what we have already, DateTime=>Millisecond, Date=>Day), and people who need it can eventually write it out themselves (which really wouldn't be that hard IMO, I could probably start a write of a nanosecond that others could follow).

@aviks, @StefanKarpinski; thoughts?

**Comment by StefanKarpinski** [comment]
My main reason for wanting to support different precision levels is that it matches what NumPy datetimes seem to do and also means that we're basically done – you never need another damned time type. I would order the type parameters as `DateTime{Millisecond,UTC,ISOCalendar}` – from most likely to need to be mentioned to least.
